// Generated by https://quicktype.io

export interface AvocadosResponse {
  length: number;
  data: SingleAvocado[];
}

export interface SingleAvocado {
  name: string;
  id: string;
  sku: string;
  price: number;
  image: string;
  attributes: Attributes;
}

export interface Attributes {
  description: string;
  shape: string;
  hardiness: string;
  taste: string;
}
